apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
spec:
  groups:
  - name: app-alerts
    rules:

    - alert: HighErrorRate
      expr: |
        (
          sum(rate(http_requests_total{status=~"5..", route=~"/|/api.*|/health"}[1m]))
          /
          sum(rate(http_requests_total{route=~"/|/api.*|/health"}[1m]))
        ) > 0.05
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "High error rate 🚨"
        description: "Error rate is above 5% for 2 minutes"

    - alert: HighLatency
      expr: |
        histogram_quantile(
          0.95,
          sum by (le) (
            rate(http_request_duration_seconds_bucket{route=~"/|/api.*|/health"}[1m])
          )
        ) > 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High latency ⚠️"
        description: "p95 latency is above 1 second"